name: Datarhei Restreamer

on:
  workflow_dispatch:

jobs:
  restreamer:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Connect to Tailscale
        run: |
          sudo tailscale up \
            --authkey="${{ secrets.TAILSCALE_AUTHKEY }}" \
            --hostname="github-restreamer"

      - name: Show Tailscale IP
        run: |
          echo "=============================="
          echo "Tailscale IPv4"
          echo "=============================="
          tailscale ip -4
          echo
          tailscale status
          echo "=============================="

      - name: Check Docker
        run: |
          docker --version

      - name: Create Restreamer folders
        run: |
          mkdir -p "$GITHUB_WORKSPACE/restreamer/config"
          mkdir -p "$GITHUB_WORKSPACE/restreamer/data"

      - name: Restore Restreamer data
        uses: actions/download-artifact@v4
        with:
          name: restreamer-data
          path: "$GITHUB_WORKSPACE/restreamer"
        continue-on-error: true

      - name: Start Datarhei Restreamer
        run: |
          docker rm -f restreamer 2>/dev/null || true

          docker run -d \
            --name restreamer \
            --restart unless-stopped \
            -v "$GITHUB_WORKSPACE/restreamer/config:/core/config" \
            -v "$GITHUB_WORKSPACE/restreamer/data:/core/data" \
            -p 8080:8080 \
            -p 8181:8181 \
            -p 1935:1935 \
            -p 1936:1936 \
            -p 6000:6000/udp \
            datarhei/restreamer:latest

      - name: Show Restreamer
        run: |
          sleep 10

          echo "=============================="
          echo "Tailscale IP:"
          tailscale ip -4
          echo "=============================="

          echo "Restreamer:"
          docker ps

          echo "=============================="
          echo "Restreamer Logs:"
          echo "=============================="

          docker logs --tail 50 restreamer

      - name: Keep Runner alive
        run: |
          echo "Restreamer is running..."
          sleep 20800

      - name: Stop Restreamer
        if: always()
        run: |
          docker stop restreamer || true

      - name: Save Restreamer data
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: restreamer-data
          path: restreamer/
          retention-days: 7
          overwrite: true
